### PR TITLE
To Do list: list structure

### PR DESCRIPTION
**Pull request by MarcoOquendoC**
# [To Do list: list structure](https://github.com/microverseinc/curriculum-javascript/blob/main/todo-list/m1_list_structure.md)

## Hi good reviewer,

Funny distracted girl

### These are the [changes](https://github.com/MarcoOquendoC/toDoList/tree/structure) proposed for the [To Do list](https://github.com/MarcoOquendoC/toDoList/tree/main) project:

For more detail refer to the [README.md](https://github.com/MarcoOquendoC/toDoList/blob/structure/README.md) file.

*Note: To check for different styles, I used some elements hard coded in the data array.*

## Project requirements
- Based webpack exercise you have already completed.
- Create an index.html with an empty To Do List placeholder. 
- Set index.html as a template using the HTML Webpack Plugin.

- Create an index.js file and set an array of some simple to do tasks (array of objects). Each task object should contain three keys:
  - description [string].
  - completed [bool].
  - index: [number].

- Write a function to iterate over the tasks array and populate an HTML list item element for each task.
- On page load render the dynamically created list of tasks in the dedicated placeholder.
- The list should appear in order of the index values for each task.
- Create a style.css and set rules for the To Do List.
- CSS must be loaded by Webpack Style/CSS Loader.
- All source files (index.html, index.js and style.css) are located in /src directory.
- Distribution files are generated by webpack and served by webpack dev server from /dist folder.

### CODE REVIEW

**Review by CollinsTatang — APPROVED** [review]
# Approved 👏  
### **Highlights 🚀 :heavy_check_mark: :heavy_check_mark:** 

- The repo looks professional.:heavy_check_mark:
- Git/GitHub flow best practices have been followed:heavy_check_mark:
- You have descriptive PR:heavy_check_mark:

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
### **Congratulations!** 🎉 
image



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @CollinsTatang in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by MarcoOquendoC** [comment]
Thank you @CollinsTatang,

I have already searched for a gif to make some changes. 🤣

**Comment by CollinsTatang** [comment]
> 

That's great, you meet the project requirements
Nevertheless you can still improve your work

**Comment by MarcoOquendoC** [comment]
I know,

Please give me some advice to make it better.

**Pull request merged**
